# 任务的名称
name: Vite project deploy to Github Page

# 事件的监听
on:
  # 监听 main 分支的 push 事件
  push:
    branches: [main]

# 执行任务
jobs:
  # 名称
  build-and-deploy:
    # 执行环境
    runs-on: macOS-latest
    # 步骤
    steps:
      # 步骤1: 检出分支
      # uses后跟着的是在Github市场上线的一些脚本
      # https://github.com/marketplace
      - uses: actions/checkout@v3

      # 步骤2: 选用 Node.js 版本
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 步骤3: 安装依赖、打包
      - name: install dependencies
        run: npm i

      - name: build
        run: npm run build

      # 步骤4: 部署到Github Pages
      - name: deploy to Github Pages
        uses: crazy-max/ghaction-github-pages@v3
        # 要部署的目标分支及要部署的文件目录
        # 即把dist目录下的内容部署到 gh-pages 分支
        with:
          target_branch: gh-pages
          build_dir: ./dist
        # 环境变量
        env:
          # 在每个工作流程运行开始时，GitHub 会自动创建唯一的 GITHUB_TOKEN 密码以在工作流程中使用。 您可以使用 GITHUB_TOKEN 在工作流程运行中进行身份验证。
          # https://github.com/marketplace/actions/github-pages#environment-variables
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}